### ISSUE TITLE
Add "Open access" button above the facets

### ISSUE THREAD

**Issue by sebastiendeleze** [rero/sonar#511]
It allows to restrict the results to open access publications, similar to the "Search in full-text" button. But contrary to the latter, it is shown all the time, even if no search query is entered.

This filter is based on the value of the file's metadata `access`. If this property is set to `restricted`, the document won't be in the results list. In all other cases, the document will appear in results list.

When importing files from HEG, if `oa_status` is `closed`, the the first file will be flagged as `restricted`. Otherwise, the file is `open_access`.

**Comment by pronguen** [comment]
@sebastiendeleze Problems encountered:
* Is it normal that a document with active embargo appears under the OA filter? Ideally it should not be the case. Only for documents whose embargo date is in the past.
* I understand that the documents from HEG not OA have received the "restricted" attribute. Problem: the link to the publisher page is not visible, since it is not possible to click on the document icon. The user can only click on the DOI link, which is not visible at all. To be improved later.
